name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours 
  workflow_dispatch: # Allows manual triggering

jobs:
  ping_app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Send HTTP request to Streamlit app
        run: |
          curl -I https://fuzzyrecommender.streamlit.app/
